/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacetec;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author babyp
 */
public class NewFormula extends javax.swing.JFrame {

    /**
     * Creates new form NewFormula
     */
    public NewFormula() {
        initComponents();
        setLocationRelativeTo(null);
        
        Color background = new Color(190,255,255); 
        this.getContentPane().setBackground(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        new_menu = new javax.swing.JButton();
        new_text = new javax.swing.JTextField();
        new_result = new javax.swing.JButton();
        new_propositions = new javax.swing.JPanel();
        new_label_prop = new javax.swing.JLabel();
        new_prop_but_A = new javax.swing.JButton();
        new_prop_but_B = new javax.swing.JButton();
        new_prop_but_C = new javax.swing.JButton();
        new_prop_but_D = new javax.swing.JButton();
        new_prop_but_E = new javax.swing.JButton();
        new_prop_but_F = new javax.swing.JButton();
        new_prop_but_V = new javax.swing.JButton();
        new_prop_but_H = new javax.swing.JButton();
        new_prop_but_I = new javax.swing.JButton();
        new_prop_but_J = new javax.swing.JButton();
        new_prop_but_K = new javax.swing.JButton();
        new_prop_but_G = new javax.swing.JButton();
        new_operators = new javax.swing.JPanel();
        new_label_oper = new javax.swing.JLabel();
        new_op_but_not = new javax.swing.JButton();
        new_op_but_or = new javax.swing.JButton();
        new_op_but_and = new javax.swing.JButton();
        new_op_but_imply = new javax.swing.JButton();
        new_prop_but_xnor = new javax.swing.JButton();
        new_op_but_openpar = new javax.swing.JButton();
        new_op_but_closepar = new javax.swing.JButton();
        new_op_but_APAGAR = new javax.swing.JButton();

        jDialog1.setTitle("Confirmação");
        jDialog1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        new_menu.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        new_menu.setText("< Menu");
        new_menu.setBorder(null);
        new_menu.setBorderPainted(false);
        new_menu.setContentAreaFilled(false);
        new_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_menuActionPerformed(evt);
            }
        });

        new_text.setEditable(false);
        new_text.setBackground(new java.awt.Color(255, 255, 255));
        new_text.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        new_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        new_result.setBackground(new java.awt.Color(255, 255, 255));
        new_result.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        new_result.setText("Result >");
        new_result.setActionCommand("Result >");
        new_result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_result.setContentAreaFilled(false);
        new_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_resultActionPerformed(evt);
            }
        });

        new_propositions.setBackground(new java.awt.Color(255, 255, 255));
        new_propositions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        new_label_prop.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        new_label_prop.setText("Propositions");

        new_prop_but_A.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_A.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_A.setText("A");
        new_prop_but_A.setToolTipText("");
        new_prop_but_A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_A.setContentAreaFilled(false);
        new_prop_but_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_AActionPerformed(evt);
            }
        });

        new_prop_but_B.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_B.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_B.setText("B");
        new_prop_but_B.setToolTipText("");
        new_prop_but_B.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_B.setContentAreaFilled(false);
        new_prop_but_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_BActionPerformed(evt);
            }
        });

        new_prop_but_C.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_C.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_C.setText("C");
        new_prop_but_C.setToolTipText("");
        new_prop_but_C.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_C.setContentAreaFilled(false);
        new_prop_but_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_CActionPerformed(evt);
            }
        });

        new_prop_but_D.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_D.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_D.setText("D");
        new_prop_but_D.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_D.setContentAreaFilled(false);
        new_prop_but_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_DActionPerformed(evt);
            }
        });

        new_prop_but_E.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_E.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_E.setText("E");
        new_prop_but_E.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_E.setContentAreaFilled(false);
        new_prop_but_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_EActionPerformed(evt);
            }
        });

        new_prop_but_F.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_F.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_F.setForeground(new java.awt.Color(255, 51, 51));
        new_prop_but_F.setText("F");
        new_prop_but_F.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        new_prop_but_F.setContentAreaFilled(false);
        new_prop_but_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_FActionPerformed(evt);
            }
        });

        new_prop_but_V.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_V.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_V.setForeground(new java.awt.Color(0, 153, 0));
        new_prop_but_V.setText("V");
        new_prop_but_V.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));
        new_prop_but_V.setContentAreaFilled(false);
        new_prop_but_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_VActionPerformed(evt);
            }
        });

        new_prop_but_H.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_H.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_H.setText("H");
        new_prop_but_H.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_H.setContentAreaFilled(false);
        new_prop_but_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_HActionPerformed(evt);
            }
        });

        new_prop_but_I.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_I.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_I.setText("I");
        new_prop_but_I.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_I.setContentAreaFilled(false);
        new_prop_but_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_IActionPerformed(evt);
            }
        });

        new_prop_but_J.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_J.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_J.setText("J");
        new_prop_but_J.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_J.setContentAreaFilled(false);
        new_prop_but_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_JActionPerformed(evt);
            }
        });

        new_prop_but_K.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_K.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_K.setText("K");
        new_prop_but_K.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_K.setContentAreaFilled(false);
        new_prop_but_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_KActionPerformed(evt);
            }
        });

        new_prop_but_G.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_G.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_G.setText("G");
        new_prop_but_G.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_G.setContentAreaFilled(false);
        new_prop_but_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_GActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout new_propositionsLayout = new javax.swing.GroupLayout(new_propositions);
        new_propositions.setLayout(new_propositionsLayout);
        new_propositionsLayout.setHorizontalGroup(
            new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_propositionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(new_label_prop)
                    .addGroup(new_propositionsLayout.createSequentialGroup()
                        .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(new_propositionsLayout.createSequentialGroup()
                                .addComponent(new_prop_but_A, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_B, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_E, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(new_propositionsLayout.createSequentialGroup()
                                .addComponent(new_prop_but_G, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(new_prop_but_H, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_I, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_J, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_prop_but_K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(new_prop_but_F, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_prop_but_V, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        new_propositionsLayout.setVerticalGroup(
            new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_propositionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new_label_prop)
                .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_propositionsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_prop_but_A, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_B, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_E, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_prop_but_H, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_I, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_J, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_G, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(new_propositionsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(new_propositionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_prop_but_F, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_prop_but_V, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        new_operators.setBackground(new java.awt.Color(255, 255, 255));
        new_operators.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        new_label_oper.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        new_label_oper.setText("Operators");
        new_label_oper.setToolTipText("");

        new_op_but_not.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_not.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_not.setText("¬");
        new_op_but_not.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_not.setContentAreaFilled(false);
        new_op_but_not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_notActionPerformed(evt);
            }
        });

        new_op_but_or.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_or.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_or.setText("OR");
        new_op_but_or.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_or.setContentAreaFilled(false);
        new_op_but_or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_orActionPerformed(evt);
            }
        });

        new_op_but_and.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_and.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_and.setText("AND");
        new_op_but_and.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_and.setContentAreaFilled(false);
        new_op_but_and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_andActionPerformed(evt);
            }
        });

        new_op_but_imply.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_imply.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_imply.setText("-->");
        new_op_but_imply.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_imply.setContentAreaFilled(false);
        new_op_but_imply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_implyActionPerformed(evt);
            }
        });

        new_prop_but_xnor.setBackground(new java.awt.Color(255, 255, 255));
        new_prop_but_xnor.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_prop_but_xnor.setText("<-->");
        new_prop_but_xnor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_prop_but_xnor.setContentAreaFilled(false);
        new_prop_but_xnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_prop_but_xnorActionPerformed(evt);
            }
        });

        new_op_but_openpar.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_openpar.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_openpar.setText("(");
        new_op_but_openpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_openpar.setContentAreaFilled(false);
        new_op_but_openpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_openparActionPerformed(evt);
            }
        });

        new_op_but_closepar.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_closepar.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_closepar.setText(")");
        new_op_but_closepar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        new_op_but_closepar.setContentAreaFilled(false);
        new_op_but_closepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_closeparActionPerformed(evt);
            }
        });

        new_op_but_APAGAR.setBackground(new java.awt.Color(255, 255, 255));
        new_op_but_APAGAR.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        new_op_but_APAGAR.setForeground(new java.awt.Color(255, 0, 0));
        new_op_but_APAGAR.setText("DELETE");
        new_op_but_APAGAR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        new_op_but_APAGAR.setContentAreaFilled(false);
        new_op_but_APAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_op_but_APAGARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout new_operatorsLayout = new javax.swing.GroupLayout(new_operators);
        new_operators.setLayout(new_operatorsLayout);
        new_operatorsLayout.setHorizontalGroup(
            new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_operatorsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_operatorsLayout.createSequentialGroup()
                        .addGroup(new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(new_operatorsLayout.createSequentialGroup()
                                .addComponent(new_op_but_not, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(new_op_but_or, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(new_op_but_and, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(new_operatorsLayout.createSequentialGroup()
                                .addComponent(new_prop_but_xnor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(new_op_but_openpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(new_op_but_closepar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(new_operatorsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(new_op_but_imply, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_operatorsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(new_op_but_APAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(new_operatorsLayout.createSequentialGroup()
                        .addComponent(new_label_oper)
                        .addContainerGap())))
        );
        new_operatorsLayout.setVerticalGroup(
            new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_operatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new_label_oper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_op_but_and, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_op_but_or, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_op_but_imply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_op_but_not, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(new_operatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_prop_but_xnor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_op_but_openpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_op_but_closepar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_operatorsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_op_but_APAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(new_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(new_propositions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(new_operators, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(new_text))
                        .addGap(18, 18, 18)
                        .addComponent(new_result, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(new_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_result, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(new_operators, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_propositions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_menuActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_new_menuActionPerformed

    private void new_op_but_openparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_openparActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "(");
    }//GEN-LAST:event_new_op_but_openparActionPerformed

    private void new_op_but_closeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_closeparActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + ")");
    }//GEN-LAST:event_new_op_but_closeparActionPerformed

    private void new_op_but_notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_notActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "¬");
    }//GEN-LAST:event_new_op_but_notActionPerformed

    private void new_op_but_orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_orActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + " OR ");
    }//GEN-LAST:event_new_op_but_orActionPerformed

    private void new_op_but_andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_andActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + " AND ");
    }//GEN-LAST:event_new_op_but_andActionPerformed

    private void new_op_but_implyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_implyActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + " --> ");
    }//GEN-LAST:event_new_op_but_implyActionPerformed

    private void new_prop_but_xnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_xnorActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + " <--> ");
    }//GEN-LAST:event_new_prop_but_xnorActionPerformed

    private void new_prop_but_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_AActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "A");
    }//GEN-LAST:event_new_prop_but_AActionPerformed

    private void new_prop_but_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_BActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "B");
    }//GEN-LAST:event_new_prop_but_BActionPerformed

    private void new_prop_but_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_CActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "C");
    }//GEN-LAST:event_new_prop_but_CActionPerformed

    private void new_prop_but_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_DActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "D");
    }//GEN-LAST:event_new_prop_but_DActionPerformed

    private void new_prop_but_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_EActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "E");
    }//GEN-LAST:event_new_prop_but_EActionPerformed

    private void new_prop_but_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_FActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "F");
    }//GEN-LAST:event_new_prop_but_FActionPerformed

    private void new_prop_but_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_VActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "V");
    }//GEN-LAST:event_new_prop_but_VActionPerformed

    private void new_prop_but_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_HActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "H");
    }//GEN-LAST:event_new_prop_but_HActionPerformed

    private void new_prop_but_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_IActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "I");
    }//GEN-LAST:event_new_prop_but_IActionPerformed

    private void new_prop_but_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_JActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "J");
    }//GEN-LAST:event_new_prop_but_JActionPerformed

    private void new_prop_but_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_KActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "K");
    }//GEN-LAST:event_new_prop_but_KActionPerformed

    private void new_prop_but_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_prop_but_GActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        new_text.setText(texto + "G");
    }//GEN-LAST:event_new_prop_but_GActionPerformed

    private void new_op_but_APAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_op_but_APAGARActionPerformed
        // TODO add your handling code here:
        String texto = new_text.getText();
        if (texto.length() > 0) {
            texto = texto.substring (0, texto.length() - 1);
        }
        new_text.setText(texto);
    }//GEN-LAST:event_new_op_but_APAGARActionPerformed

    private void new_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_resultActionPerformed
            // TODO add your handling code here:
            
            Object[] options = { "Confirm", "Cancel" };
            UIManager.put("OptionPane.minimumSize", new Dimension(500, 100));
            UIManager.getDefaults().put("OptionPane.background",new Color(190,255,255));
            UIManager.put ("Panel.background", new Color(190,255,255));
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Arial", Font.BOLD, 18)));     
            
            int o = JOptionPane.showOptionDialog(null, "The formula entered was: " + new_text.getText(), "Confirmation", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            //System.out.println(o);    
            if (o == 0){
                new Result().setVisible(true);
                this.setVisible(false);
            }
            
    }//GEN-LAST:event_new_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFormula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel new_label_oper;
    private javax.swing.JLabel new_label_prop;
    private javax.swing.JButton new_menu;
    private javax.swing.JButton new_op_but_APAGAR;
    private javax.swing.JButton new_op_but_and;
    private javax.swing.JButton new_op_but_closepar;
    private javax.swing.JButton new_op_but_imply;
    private javax.swing.JButton new_op_but_not;
    private javax.swing.JButton new_op_but_openpar;
    private javax.swing.JButton new_op_but_or;
    private javax.swing.JPanel new_operators;
    private javax.swing.JButton new_prop_but_A;
    private javax.swing.JButton new_prop_but_B;
    private javax.swing.JButton new_prop_but_C;
    private javax.swing.JButton new_prop_but_D;
    private javax.swing.JButton new_prop_but_E;
    private javax.swing.JButton new_prop_but_F;
    private javax.swing.JButton new_prop_but_G;
    private javax.swing.JButton new_prop_but_H;
    private javax.swing.JButton new_prop_but_I;
    private javax.swing.JButton new_prop_but_J;
    private javax.swing.JButton new_prop_but_K;
    private javax.swing.JButton new_prop_but_V;
    private javax.swing.JButton new_prop_but_xnor;
    private javax.swing.JPanel new_propositions;
    private javax.swing.JButton new_result;
    private javax.swing.JTextField new_text;
    // End of variables declaration//GEN-END:variables
}
